Name:           ros-hydro-pr2-2dnav
Version:        1.0.1
Release:        0%{?dist}
Summary:        ROS pr2_2dnav package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_2dnav
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-pr2-machine
Requires:       ros-hydro-pr2-navigation-global
Requires:       ros-hydro-pr2-navigation-perception
Requires:       ros-hydro-pr2-navigation-teleop
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-pr2-machine
BuildRequires:  ros-hydro-pr2-navigation-global
BuildRequires:  ros-hydro-pr2-navigation-perception
BuildRequires:  ros-hydro-pr2-navigation-teleop

%description
This application allows the PR2 robot to navigate autonomously with a pre-
specified static map.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Sep 16 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.1-0
- Autogenerated by Bloom

